-- MySQL Script generated by MySQL Workbench
-- Mon Jul  5 15:08:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Telephone directory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Telephone directory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Telephone directory` DEFAULT CHARACTER SET utf8 ;
USE `Telephone directory` ;

-- -----------------------------------------------------
-- Table `Telephone directory`.`Peoples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Telephone directory`.`Peoples` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) INVISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Telephone directory`.`Phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Telephone directory`.`Phones` (
  `PeopleID` INT UNSIGNED NOT NULL,
  `Phone` INT NULL,
  UNIQUE INDEX `Phonescol_UNIQUE` (`Phone` ASC) VISIBLE,
  INDEX `People_idx` (`PeopleID` ASC) VISIBLE,
  CONSTRAINT `People`
    FOREIGN KEY (`PeopleID`)
    REFERENCES `Telephone directory`.`Peoples` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Telephone directory`.`Mails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Telephone directory`.`Mails` (
  `PeopleID` INT UNSIGNED NOT NULL,
  `Mail` VARCHAR(45) NULL,
  UNIQUE INDEX `Mail_UNIQUE` (`Mail` ASC),
  CONSTRAINT `Mail`
    FOREIGN KEY (`PeopleID`)
    REFERENCES `Telephone directory`.`Peoples` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
